[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "octopy"
version = "5.2.9post1"
description = "Command line tool layout analysis and OCR of historical prints using Kraken."
keywords = ["PageXML", "XML", "OCR", "optical character recognition", "kraken"]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.11"
authors = [
    { name = "Janik Haitz", email = "jahtz.dev@proton.me" },
    { name = "Centre for Philology and Digitality (ZPD), University of Würzburg" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "kraken",
    "pypxml ~= 4.2.3",
    "click ~= 8.1.8",
    "rich ~= 14.0.0"
]

[project.urls]
Homepage = "https://www.uni-wuerzburg.de/zpd/"
Repository = "https://github.com/jahtz/octopy"

[tool.hatch.build.targets.wheel]
include = ["octopy", "cli"]

[project.scripts]
octopy = "cli.octopy_cli:cli"
